//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCI_Escalate.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientBusinessUnit
    {
        public long Id { get; set; }
        public Nullable<long> ClientId { get; set; }
        public Nullable<long> BusinessUnitId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Client Client { get; set; }
    }
}
